### ISSUE TITLE
Add Georgia Tech to affiliates

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-website#112]
https://allennlp.org/

![image](https://user-images.githubusercontent.com/954798/50600899-688cf780-0e67-11e9-9c96-cc7ccd676716.png)

**Comment by schmmd** [comment]
@aaronsarnat our tiles are presently nice and symmetrical (we don't have any partial rows).  As we add more should we just start adding new additions to the next row?

**Comment by aaronsarnat** [comment]
@schmmd If maintaining a clean, professional presentation of logos is important to AllenNLP then I have some thoughts on how to proceed:

1. **Optimization vs maintainability** - There's an optimization vs maintainability tradeoff. The first rev (before we spruced it up) was more scrappy and thus more easily extendable, as there were no constraints. The downside was that it didn't look as professional and wasn't very well optimized in terms of its design or asset production for web use. The current implementation is more heavily optimized, but is also more constrained and requires more effort to extend while maintaining the same level of quality.

2. **Logo cap** - I think we should cap the number of logos we add to the home page. There comes a point where a grid with too many "featured" logos becomes information overload and loses its effectiveness at communicating at-a-glance "look who's using our stuff." We're already at a comfortable number of rows. I'd say we could maybe get away with 1 more row, but I would caution against more than that, as I believe we'd be entering the realm of diminishing returns. If we go this route then we would obviously need to be more selective about which logos we feature.

    - **Batching logos** - I think we may also want to batch new logos, waiting until we have an additional row's worth before adding more. This would keep the grid always looking nice and also give the update work an efficiency bump with a bit of economy of scale. What does your gut tell you? Could the featured grid potentially go months between updates?

    - **Catch-all logo page** - If we want to have our cake and eat it too, we could keep a compact featured logo grid on the home page with maybe 2-3 rows and then add a "see all of our affiliates" link that points to a page that is just a giant logo dump with fewer design constraints. That might satisfy any concerns about certain logos being MIA. I know I just said too many logos is information overload, but the difference here is that: a) logos are not competing for attention with other information, as is the case currently with the home page, and b) the user is taking an explicit action to view more logos, so it wouldn't need to serve the "at-a-glance" use case. In essence, we could add additional one-off logos as often as we like to the comprehensive list while rarely having to make updates to the home page grid.

On the other hand, if we want to be more lax about how we handle featured logos for the sake of maintainability, we could just add more assets as needed with the understanding that we'll have partial rows and some grid imbalance, as logos come in all shapes and sizes. The current grid was arranged (and each logo sized) so that all the logos looked balanced relative to each other, but perhaps AllenNLP doesn't require that level of design scrutiny?

**Comment by schmmd** [comment]
My recommendation is that we have a grid that looks good and a full list of people who use AllenNLP on another page in a list.
