### ISSUE TITLE
Incorporate new AI2-branded web header into AllenNLP website

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-website#71]
We're blocked on this until Nick prototypes something with Semantic Scholar.

Oren would like a stronger AI2 emblem than what we currently have on AllenNLP.  In particular, he would like us to incorporate 
![image](https://user-images.githubusercontent.com/954798/45127884-7d62b400-b12f-11e8-91a0-27cb2d4e53c8.png) into the header.

**Comment by schmmd** [comment]
We're going to go with the first variation in this slide deck: https://docs.google.com/presentation/d/1EVQ9P6fb5GvHngUV_EUR-m3GZJfliXLNw-5BqYUtw7I/edit?usp=sharing

**Comment by schmmd** [comment]
![image](https://user-images.githubusercontent.com/954798/46444262-0caab980-c726-11e8-981d-21c635881a4b.png)

@splittingfield please confirm this is the design we're going with, just to be crystal clear ;-)

**Comment by splittingfield** [comment]
Yep! Our version in dev (requires VPN)  https://leaderboard.dev.allenai.org/

 Please chat with @systemride and @jonborchardt  to see if you all require any size adjustments or color pallettes.  I believe we made some minor changes around this.

**Comment by schmmd** [comment]
@systemride can you point us to the specific assets we should use?

**Comment by schmmd** [comment]
@jonborchardt this is where we're tracking updating the AllenNLP website.  That said, I think Aaron will take it from here.  He might try tweaking some of the coloring on our website as we're adding a white stripe on top.

**Comment by jonborchardt** [comment]
Sounds good.  Let me know if I can help.

Here is the code we used:
```
 <a href="https://allenai.org/"><Logo src="/assets/images/ai2-logo-header.png" /></a>
 <Chevron src="/assets/images/chevron.svg" />
 <a href="/"><BeakerLogo src="/assets/images/logo-leaderboard.svg" /></a>

const BeakerLogo = styled.img`
  height: 34px;
  width: auto;
  margin-left: -20px;
`;

const Chevron = styled.img`
  height: 88px;
  width: auto;
`;

const Logo = styled.img`
  height: 55px;
  width: auto;
  margin: -4px -5px 0 0;
`;

```

https://github.com/allenai/leaderboard/blob/develop/ui/src/components/layout/TopBar.tsx

**Comment by aaronsarnat** [comment]
@schmmd @carissas @jonborchardt @splittingfield @systemride This is what I think makes the most sense for AllenNLP (at least in the short term), and this is what I'm planning to implement unless anyone has any concerns/objections?
<br>

### [6-page Invision Click-through](https://invis.io/5QOFPWO4AFR#/324048540_Allennlp-Header-Desktop1)
<br>

**FYIs:**

1. Nick mocked up a direction for AllenNLP that kept the black header for us (good looking out, Nick!), but I thought it might make more sense to just invert our header and keep a look and feel consistent with the headers for the other web properties. I think white works fine.

2. With a white background, I tweaked the colors of the AllenNLP logo. Now using **Beaker Gray**™ with a bit of blue.

3. Since AllenNLP is a wider site than Beaker/Leaderboard, the header left/right content is anchored to the current AllenNLP left/right extremities (i.e. the header is wider overall, but the elements that make up the header content should match Beaker/Leaderboard).

4. Current AllenNLP site supports mobile, so I needed a mobile solution (it appeared that mobile header hadn't been taken into account yet on Beaker or Leaderboard, at least not visible via the dev links that I have). What I mocked up at the end of the click-through would be a low-hanging fruit solution that:
    - Retains the new look and feel
    - Follows what we're currently doing on http://allenai.org re: logo treatment for mobile
    - Uses existing mechanics 

---

I'm going to take a 1-hr break and then plan to start working on a PR to reflect what I mocked up as soon as I get back...
<br>

**Comment by schmmd** [comment]
:ship:
